#OPERADORES DE COMPARAÇÃO

#OPERADOR DA IGUALDADE: ==
#OPERADOR DE ATRIBUIÇÃO: = 
#OPERADOR DA DIFERENÇA: !=
#OPERADOR MAIOR QUE: >
#OPERADOR MENOR QUE: <
#OPERADOR MAIOR QUE OU IGUAL A: >=
#OPERADOR MENOR QUE OU IGUAL A: <=

#OPERADOR DE ATRIBUIÇÃO =

x = 3
y = 5
z = 3.0
w = 8

print(x >= y)